# Generated file that can be used to preload variant images
set(BOARD "xiao_ble" CACHE INTERNAL "NCS child image controlled")
set(BOARD_ROOT "c:/_projects/nrf_spi;C:/ncs/v2.6.0/nrf;C:/ncs/v2.6.0/zephyr" CACHE INTERNAL "NCS child image controlled")
set(CACHED_CONF_FILE "c:/_projects/nRF_SPI/prj.conf" CACHE INTERNAL "NCS child image controlled")
set(CONF_FILE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE "C:/_projects/nRF_SPI/boards/xiao_ble.overlay" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_DTC_OVERLAY_FILE "boards/xiao_ble.overlay" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_DTC_OVERLAY_FILE "boards/xiao_ble.overlay" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "NONE" CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON "C:/ncs/toolchains/cf2149caf2/opt/bin/python.exe" CACHE INTERNAL "NCS child image controlled")
